-- Create a table for user profiles
create table profiles (
  id uuid references auth.users not null primary key,
  xp integer default 0,
  level integer default 1,
  streak integer default 0,
  last_active_date date,
  full_name text,
  avatar_url text
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create policies
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup (Optional: Auto-create profile)
/*
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
*/

-- Goals Table Reference (Inferred)
/*
create table goals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text text,
  done boolean default false,
  target_date date,
  category text,
  priority integer default 1,
  estimated_minutes integer,
  completed_sessions integer default 0,
  focus_span integer default 25,
  mode text default 'normal',
  type text default 'daily',
  user_id uuid references auth.users
);
*/

-- NEW MIGRATION: Add parent_id for Subtasks/Project Backlog
-- Run this in Supabase SQL Editor
-- ALTER TABLE goals ADD COLUMN parent_id bigint REFERENCES goals(id);
